{
 "title": "Hbase",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "SERVICENAME" }
  ]
 },
 "panels": [
  { "title": "RegionServer: Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Regions",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select total_regions_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Total Resident Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select total_mem_rss_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Total Swap Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select mem_swap_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "OOM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select oom_exits_rate_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Unexpected PS Exit",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select total_unexpected_exits_rate_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Total BlockCache Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select total_block_cache_blocks_cached_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Parallel GC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 5 },
   "targets": [
    {
     "target": "select integral(gc_count_par_new_rate_across_regionservers) where entityName=hbase"
    }
   ]
  },
  {
   "title": "Parallel GC time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 5 },
   "targets": [
    {
     "target": "select integral(gc_time_ms_par_new_rate_across_regionservers) where entityName=hbase"
    }
   ]
  },
  {
   "title": "Webserver Responsiveness",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "target": "select web_metrics_collection_duration_across_regionservers where entityName=hbase"
    }
   ]
  },
  { "title": "RegionServer: BlockCache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Hit Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select block_cache_hit_rate_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Miss Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select block_cache_miss_rate_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Free Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select total_block_cache_free_size_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Total Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select total_block_cache_size_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Eviction Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select block_cache_evicted_rate_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "target": "select block_cache_hit_ratio_across_regionservers where entityName=hbase"
    }
   ]
  },
  {
   "title": "Total Size Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "select total_block_cache_size_across_regionservers where entityName=hbase"
    }
   ]
  }
 ]
}